// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ca.proto
// Protobuf Java Version: 4.30.2

package com.alibaba.csp.sentinel.datasource.xds.client.grpc;

public final class Ca {
  private Ca() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Ca.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\010ca.proto\0223com.alibaba.csp.sentinel.dat" +
      "asource.xds.client.grpc\032\034google/protobuf" +
      "/struct.proto\"l\n\027IstioCertificateRequest" +
      "\022\013\n\003csr\030\001 \001(\t\022\031\n\021validity_duration\030\003 \001(\003" +
      "\022)\n\010metadata\030\004 \001(\0132\027.google.protobuf.Str" +
      "uct\".\n\030IstioCertificateResponse\022\022\n\ncert_" +
      "chain\030\001 \003(\t2\316\001\n\027IstioCertificateService\022" +
      "\262\001\n\021CreateCertificate\022L.com.alibaba.csp." +
      "sentinel.datasource.xds.client.grpc.Isti" +
      "oCertificateRequest\032M.com.alibaba.csp.se" +
      "ntinel.datasource.xds.client.grpc.IstioC" +
      "ertificateResponse\"\000B%P\001Z\036istio.io/api/s" +
      "ecurity/v1alpha1\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor,
        new String[] { "Csr", "ValidityDuration", "Metadata", });
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor,
        new String[] { "CertChain", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
