// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ca.proto
// Protobuf Java Version: 4.30.2

package com.alibaba.csp.sentinel.datasource.xds.client.grpc;

/**
 * <pre>
 * Certificate response message.
 * </pre>
 *
 * Protobuf type {@code com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse}
 */
public final class IstioCertificateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse)
    IstioCertificateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      IstioCertificateResponse.class.getName());
  }
  // Use IstioCertificateResponse.newBuilder() to construct.
  private IstioCertificateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IstioCertificateResponse() {
    certChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            IstioCertificateResponse.class, Builder.class);
  }

  public static final int CERT_CHAIN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList certChain_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * PEM-encoded certificate chain.
   * The leaf cert is the first element, and the root cert is the last element.
   * </pre>
   *
   * <code>repeated string cert_chain = 1;</code>
   * @return A list containing the certChain.
   */
  public com.google.protobuf.ProtocolStringList
      getCertChainList() {
    return certChain_;
  }
  /**
   * <pre>
   * PEM-encoded certificate chain.
   * The leaf cert is the first element, and the root cert is the last element.
   * </pre>
   *
   * <code>repeated string cert_chain = 1;</code>
   * @return The count of certChain.
   */
  public int getCertChainCount() {
    return certChain_.size();
  }
  /**
   * <pre>
   * PEM-encoded certificate chain.
   * The leaf cert is the first element, and the root cert is the last element.
   * </pre>
   *
   * <code>repeated string cert_chain = 1;</code>
   * @param index The index of the element to return.
   * @return The certChain at the given index.
   */
  public String getCertChain(int index) {
    return certChain_.get(index);
  }
  /**
   * <pre>
   * PEM-encoded certificate chain.
   * The leaf cert is the first element, and the root cert is the last element.
   * </pre>
   *
   * <code>repeated string cert_chain = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the certChain at the given index.
   */
  public com.google.protobuf.ByteString
      getCertChainBytes(int index) {
    return certChain_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {return true;}
    if (isInitialized == 0) {return false;}

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < certChain_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, certChain_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {return size;}

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < certChain_.size(); i++) {
        dataSize += computeStringSizeNoTag(certChain_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCertChainList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof IstioCertificateResponse)) {
      return super.equals(obj);
    }
    IstioCertificateResponse other = (IstioCertificateResponse) obj;

    if (!getCertChainList()
        .equals(other.getCertChainList())) {return false;}
    if (!getUnknownFields().equals(other.getUnknownFields())) {return false;}
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCertChainCount() > 0) {
      hash = (37 * hash) + CERT_CHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getCertChainList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static IstioCertificateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static IstioCertificateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static IstioCertificateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static IstioCertificateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static IstioCertificateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static IstioCertificateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(IstioCertificateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Certificate response message.
   * </pre>
   *
   * Protobuf type {@code com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse)
      IstioCertificateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IstioCertificateResponse.class, Builder.class);
    }

    // Construct using com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      certChain_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateResponse_descriptor;
    }

    @Override
    public IstioCertificateResponse getDefaultInstanceForType() {
      return IstioCertificateResponse.getDefaultInstance();
    }

    @Override
    public IstioCertificateResponse build() {
      IstioCertificateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public IstioCertificateResponse buildPartial() {
      IstioCertificateResponse result = new IstioCertificateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(IstioCertificateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        certChain_.makeImmutable();
        result.certChain_ = certChain_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof IstioCertificateResponse) {
        return mergeFrom((IstioCertificateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(IstioCertificateResponse other) {
      if (other == IstioCertificateResponse.getDefaultInstance()) {return this;}
      if (!other.certChain_.isEmpty()) {
        if (certChain_.isEmpty()) {
          certChain_ = other.certChain_;
          bitField0_ |= 0x00000001;
        } else {
          ensureCertChainIsMutable();
          certChain_.addAll(other.certChain_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              ensureCertChainIsMutable();
              certChain_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList certChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCertChainIsMutable() {
      if (!certChain_.isModifiable()) {
        certChain_ = new com.google.protobuf.LazyStringArrayList(certChain_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @return A list containing the certChain.
     */
    public com.google.protobuf.ProtocolStringList
        getCertChainList() {
      certChain_.makeImmutable();
      return certChain_;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @return The count of certChain.
     */
    public int getCertChainCount() {
      return certChain_.size();
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param index The index of the element to return.
     * @return The certChain at the given index.
     */
    public String getCertChain(int index) {
      return certChain_.get(index);
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the certChain at the given index.
     */
    public com.google.protobuf.ByteString
        getCertChainBytes(int index) {
      return certChain_.getByteString(index);
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param index The index to set the value at.
     * @param value The certChain to set.
     * @return This builder for chaining.
     */
    public Builder setCertChain(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCertChainIsMutable();
      certChain_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param value The certChain to add.
     * @return This builder for chaining.
     */
    public Builder addCertChain(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCertChainIsMutable();
      certChain_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param values The certChain to add.
     * @return This builder for chaining.
     */
    public Builder addAllCertChain(
        Iterable<String> values) {
      ensureCertChainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, certChain_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCertChain() {
      certChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     * @param value The bytes of the certChain to add.
     * @return This builder for chaining.
     */
    public Builder addCertChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCertChainIsMutable();
      certChain_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateResponse)
  private static final IstioCertificateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new IstioCertificateResponse();
  }

  public static IstioCertificateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IstioCertificateResponse>
      PARSER = new com.google.protobuf.AbstractParser<IstioCertificateResponse>() {
    @Override
    public IstioCertificateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IstioCertificateResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<IstioCertificateResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public IstioCertificateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

