// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ca.proto
// Protobuf Java Version: 4.30.2

package com.alibaba.csp.sentinel.datasource.xds.client.grpc;

/**
 * <pre>
 * Certificate request message. The authentication should be based on:
 * 1. Bearer tokens carried in the side channel;
 * 2. Client-side certificate via Mutual TLS handshake.
 * Note: the service implementation is REQUIRED to verify the authenticated caller is authorize to
 * all SANs in the CSR. The server side may overwrite any requested certificate field based on its
 * policies.
 * </pre>
 *
 * Protobuf type {@code com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest}
 */
public final class IstioCertificateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest)
    IstioCertificateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      IstioCertificateRequest.class.getName());
  }
  // Use IstioCertificateRequest.newBuilder() to construct.
  private IstioCertificateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IstioCertificateRequest() {
    csr_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            IstioCertificateRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int CSR_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object csr_ = "";
  /**
   * <pre>
   * PEM-encoded certificate request.
   * The public key in the CSR is used to generate the certificate,
   * and other fields in the generated certificate may be overwritten by the CA.
   * </pre>
   *
   * <code>string csr = 1;</code>
   * @return The csr.
   */
  @Override
  public String getCsr() {
    Object ref = csr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      csr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PEM-encoded certificate request.
   * The public key in the CSR is used to generate the certificate,
   * and other fields in the generated certificate may be overwritten by the CA.
   * </pre>
   *
   * <code>string csr = 1;</code>
   * @return The bytes for csr.
   */
  @Override
  public com.google.protobuf.ByteString
      getCsrBytes() {
    Object ref = csr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      csr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALIDITY_DURATION_FIELD_NUMBER = 3;
  private long validityDuration_ = 0L;
  /**
   * <pre>
   * Optional: requested certificate validity period, in seconds.
   * </pre>
   *
   * <code>int64 validity_duration = 3;</code>
   * @return The validityDuration.
   */
  @Override
  public long getValidityDuration() {
    return validityDuration_;
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  private com.google.protobuf.Struct metadata_;
  /**
   * <pre>
   * $hide_from_docs
   * Optional: Opaque metadata provided by the XDS node to Istio.
   * Supported metadata: WorkloadName, WorkloadIP, ClusterID
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  @Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * $hide_from_docs
   * Optional: Opaque metadata provided by the XDS node to Istio.
   * Supported metadata: WorkloadName, WorkloadIP, ClusterID
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return The metadata.
   */
  @Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * $hide_from_docs
   * Optional: Opaque metadata provided by the XDS node to Istio.
   * Supported metadata: WorkloadName, WorkloadIP, ClusterID
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   */
  @Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {return true;}
    if (isInitialized == 0) {return false;}

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(csr_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, csr_);
    }
    if (validityDuration_ != 0L) {
      output.writeInt64(3, validityDuration_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {return size;}

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(csr_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, csr_);
    }
    if (validityDuration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, validityDuration_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof IstioCertificateRequest)) {
      return super.equals(obj);
    }
    IstioCertificateRequest other = (IstioCertificateRequest) obj;

    if (!getCsr()
        .equals(other.getCsr())) {return false;}
    if (getValidityDuration()
        != other.getValidityDuration()) {return false;}
    if (hasMetadata() != other.hasMetadata()) {return false;}
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) {return false;}
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {return false;}
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CSR_FIELD_NUMBER;
    hash = (53 * hash) + getCsr().hashCode();
    hash = (37 * hash) + VALIDITY_DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidityDuration());
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static IstioCertificateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IstioCertificateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IstioCertificateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static IstioCertificateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static IstioCertificateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static IstioCertificateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static IstioCertificateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static IstioCertificateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(IstioCertificateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Certificate request message. The authentication should be based on:
   * 1. Bearer tokens carried in the side channel;
   * 2. Client-side certificate via Mutual TLS handshake.
   * Note: the service implementation is REQUIRED to verify the authenticated caller is authorize to
   * all SANs in the CSR. The server side may overwrite any requested certificate field based on its
   * policies.
   * </pre>
   *
   * Protobuf type {@code com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest)
      IstioCertificateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IstioCertificateRequest.class, Builder.class);
    }

    // Construct using com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetMetadataFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      csr_ = "";
      validityDuration_ = 0L;
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Ca.internal_static_com_alibaba_csp_sentinel_datasource_xds_client_grpc_IstioCertificateRequest_descriptor;
    }

    @Override
    public IstioCertificateRequest getDefaultInstanceForType() {
      return IstioCertificateRequest.getDefaultInstance();
    }

    @Override
    public IstioCertificateRequest build() {
      IstioCertificateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public IstioCertificateRequest buildPartial() {
      IstioCertificateRequest result = new IstioCertificateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(IstioCertificateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.csr_ = csr_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.validityDuration_ = validityDuration_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof IstioCertificateRequest) {
        return mergeFrom((IstioCertificateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(IstioCertificateRequest other) {
      if (other == IstioCertificateRequest.getDefaultInstance()) {return this;}
      if (!other.getCsr().isEmpty()) {
        csr_ = other.csr_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getValidityDuration() != 0L) {
        setValidityDuration(other.getValidityDuration());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              csr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 24: {
              validityDuration_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object csr_ = "";
    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     * @return The csr.
     */
    public String getCsr() {
      Object ref = csr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        csr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     * @return The bytes for csr.
     */
    public com.google.protobuf.ByteString
        getCsrBytes() {
      Object ref = csr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        csr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     * @param value The csr to set.
     * @return This builder for chaining.
     */
    public Builder setCsr(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      csr_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCsr() {
      csr_ = getDefaultInstance().getCsr();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     * @param value The bytes for csr to set.
     * @return This builder for chaining.
     */
    public Builder setCsrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      csr_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long validityDuration_ ;
    /**
     * <pre>
     * Optional: requested certificate validity period, in seconds.
     * </pre>
     *
     * <code>int64 validity_duration = 3;</code>
     * @return The validityDuration.
     */
    @Override
    public long getValidityDuration() {
      return validityDuration_;
    }
    /**
     * <pre>
     * Optional: requested certificate validity period, in seconds.
     * </pre>
     *
     * <code>int64 validity_duration = 3;</code>
     * @param value The validityDuration to set.
     * @return This builder for chaining.
     */
    public Builder setValidityDuration(long value) {

      validityDuration_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional: requested certificate validity period, in seconds.
     * </pre>
     *
     * <code>int64 validity_duration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidityDuration() {
      bitField0_ = (bitField0_ & ~0x00000002);
      validityDuration_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest)
  }

  // @@protoc_insertion_point(class_scope:com.alibaba.csp.sentinel.datasource.xds.client.grpc.IstioCertificateRequest)
  private static final IstioCertificateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new IstioCertificateRequest();
  }

  public static IstioCertificateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IstioCertificateRequest>
      PARSER = new com.google.protobuf.AbstractParser<IstioCertificateRequest>() {
    @Override
    public IstioCertificateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IstioCertificateRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<IstioCertificateRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public IstioCertificateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

